use_frameworks!

platform :ios, '9.0'

target 'HXWRefresh_Example' do
  pod 'HXWRefresh', :path => '../'
  #pod 'HXWRefresh'
  target 'HXWRefresh_Tests' do
    inherit! :search_paths
  end

#设置CODE_SIGN_IDENTITY为空来避免报错
post_install do |installer|
 installer.generated_projects.each do |project|
 project.targets.each do |target|
 target.build_configurations.each do |config|
 config.build_settings["CODE_SIGN_IDENTITY"] = ""
 end
 end
 end
end

end
